= Narayana Checkstyle Configuration

This repository contains the checkstyle rules used by some narayana projects.

== How to build

Compile with Maven.

[source,bash]
----
mvn clean install
----

== How to release

Release is performed to https://repository.jboss.org/nexus/[JBoss Nexus].

Credentials for release needs to be setup in the `~/.m2/settings.xml` (or settings defined with `-s` parameter)
where you link the repository id `jboss-releases-repository` with the username/password.

```xml
<server>
    <id>jboss-releases-repository</id>
    <username>[username]</username>
    <password>[password for jboss nexus connection]</password>
</server>
```

As the next step run the `mvn release` and proceed standard
http://maven.apache.org/maven-release/maven-release-plugin/usage.html[steps for maven release plugin].

* `git checkout main; git fetch upstream main; git rebase upstream/main; git push upstream main`
* `mvn javadoc:javadoc` - verification that there won't be any javadoc errors during `release:perform`

* `mvn release:clean`
* `mvn release:prepare`
* `mvn release:perform`

Dry run: `mvn release:prepare -DdryRun=true`

